/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package org.kotlin.mpp.mobile

expect fun platformName(): String

fun createApplicationScreenMessage() : String {
  return "Kotlin Rocks on ${platformName()}"
}
